baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "MrCroxx's Blog"
theme = 'typo'

# Google analytics code
googleAnalytics = "G-566T1L2G7S"

[taxonomies]
tag = 'tags'
category = 'categories'

[params]
# Meta description
description = "MrCroxx's Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdownT
homeIntroContent = """
# Hi

I am ***Yao Meng*** (***Â≠üÁàª***), also known as **MrCroxx** (***ÂèâÈ∏Ω***).

I'm a **software engineer** focusing on **distributed storage systems**.

My work and interests span **databases**, **distributed systems**, **storage**, **performance optimization**, **kernels**, and **open-source software**. I enjoy exploring how systems behave, how they fail, and how to make them faster and more reliable.

Outside of engineering, I have a deep appreciation for **film** üìΩÔ∏è and a quiet fondness for **beer** üç∫. Feel free to share your recommendations.

# Recent Work

Author of

- [**Foyer**](https://github.com/foyer-rs/foyer), a hybrid cache library in Rust.

Contributor of

- [**RisingWave**](https://github.com/risingwavelabs/risingwave), SQL stream processing, analytics, and management.
- [**TiKV**](https://github.com/tikv/tikv), distributed transactional key-value database.
- [**Chroma**](https://github.com/chroma-core/chroma), embedding database for LLM apps.
- ... and several other open-source projects.

# Chinese Blog (Legacy)

I previously wrote technical articles in Chinese on [ÂèâÈ∏Ω MrCroxx ÁöÑÂçöÂÆ¢](https://blogx.mrcroxx.com), mostly on **etcd/Raft**, **LevelDB**, **boltdb**, and various **paper readings**.

I have synchronized some of my previous Chinese blog posts to this site. Their titles will start with "(Chinese)" for distinction.

# Happy Reading

INFP | he/him | Want to watch more films & drink more beer. üç∫

![yao](yao.jpg#p40)

"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/mrcroxx"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/mrcroxx/"

[[params.social]]
name = "twitter"
url = "https://twitter.com/CroxxMr/"

[[params.social]]
name = "douban"
url = "https://www.douban.com/people/mrcroxx/"

[[params.social]]
name = "gmail"
url = "mailto:mrcroxx.cs@gmail.com"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "categories"
url = "/categories"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "resume‚òÖ"
url = "/resume.pdf"

[markup]

# Syntax highlight on code blocks
[markup.highlight]
style = 'friendly'

# Table of Contents
[markup.tableOfContents]
startLevel = 2
endLevel = 4

# Giscus comments
[params.giscus]
enable = true
repo = "mrcroxx/blog"
repoid = "MDEwOlJlcG9zaXRvcnkyMzM5ODI1OTQ="
category = "Giscus Comments"
categoryid = "DIC_kwDODfJKgs4CwTlA"
mapping = "pathname"
theme = "preferred_color_scheme"